GET http://localhost:3000/api/clientes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDgzZmViYmQyMWU0ZDYyZjQwOGRlMTciLCJjYWR1Y2EiOjE2MTkyNjM3NjksImlhdCI6MTYxOTI2MzE2OX0.H7kFYW7tII19k7e6RV0wnNArXevcqWip6bzWUOazkWw

###
POST http://localhost:3000/api/clientes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDgzZmViYmQyMWU0ZDYyZjQwOGRlMTciLCJjYWR1Y2EiOjE2MTkyNjM3NjksImlhdCI6MTYxOTI2MzE2OX0.H7kFYW7tII19k7e6RV0wnNArXevcqWip6bzWUOazkWw

{
    "nombre": "garcia",
    "apellidos": "martín",
    "email": "rosa@aq.it",
    "cuota": 10,
    "activo": true,
    "dni": "22222222S"
}

###
PUT http://localhost:3000/api/clientes/604bf7059c7167039825381c
Content-Type: application/json

{
    "nombre" : "Ana",
    "apellidos" : "González",
    "email" : "anagon@gmail.com",
    "cuota" : 20,
    "activo" : true
}

###
DELETE http://localhost:3000/api/clientes/604bf7059c7167039825381c

###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "usuarioAdmin",
    "email": "usuarioAdmin@mail.com",
    "password": "holaMundo123"
}

###
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "usuarioAdmin@mail.com",
    "password": "holaMundo123"
}